<?php
require_once __DIR__.'/php/features.php';
function esc($v): string {return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
try {$f=feature_get();} catch(Throwable $e){http_response_code(503);exit('This page is temporarily unavailable. Please try again shortly.');}
header('Cache-Control: no-store');
if (!$f['enabled']) {http_response_code(404);exit('This feature has ended. <a href="/">Return to Liberty Church</a>');}
$notice='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
 verify_csrf($_POST['csrf_token']??null);
 $name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$message=trim($_POST['message']??'');
 if (!empty($_POST['website'])) {$notice='Thank you for your message.';}
 elseif ($name==='' || strlen($name)>120 || !filter_var($email,FILTER_VALIDATE_EMAIL) || strlen($email)>254 || strlen($phone)>40 || $message==='' || strlen($message)>5000) {$notice='Please enter your name, a valid email, and a message (up to 5,000 characters).';}
 elseif (time()-($_SESSION['occ_last_sent']??0)<60) {$notice='Please wait a minute before sending another message.';}
 else {try {$q=db()->prepare('INSERT INTO feature_contacts (name,email,phone,message) VALUES (?,?,?,?)');$q->execute([$name,$email,$phone,$message]);$_SESSION['occ_last_sent']=time();$_SESSION['occ_sent']=true;header('Location: /operation-christmas-child#contact');exit;}catch(Throwable $e){$notice='Your message could not be saved. Please try again or call an organizer.';}}
}
if (!empty($_SESSION['occ_sent'])) {$notice='Thank you! Your message has been received by the church team.';unset($_SESSION['occ_sent']);}
$video=feature_video($f['video']);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=esc($f['title'])?> | Liberty Church</title><meta name="description" content="<?=esc($f['description'])?>"><meta property="og:title" content="Operation Christmas Child | Liberty Church"><meta property="og:description" content="Pack a shoebox. Share the love of Christ."><meta property="og:image" content="https://www.golibertychurch.com<?=esc($f['share_image'])?>"><meta property="og:url" content="https://www.golibertychurch.com/operation-christmas-child"><meta property="og:type" content="website"><meta property="og:image:alt" content="Operation Christmas Child at Liberty Church"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Operation Christmas Child | Liberty Church"><meta name="twitter:description" content="Pack a shoebox. Share the love of Christ."><meta name="twitter:image" content="https://www.golibertychurch.com<?=esc($f['share_image'])?>"><link rel="canonical" href="https://www.golibertychurch.com/operation-christmas-child"><link rel="stylesheet" href="/assets/style.css"><link rel="stylesheet" href="/assets/occ.css"></head><body class="occ-page">
<?php require __DIR__.'/includes/header.php';?>
<main><img src="/assets/operation-christmas-child.jpg" alt="Operation Christmas Child at Liberty Church" style="display:block;width:100%;max-width:1500px;margin:auto">
<div class="occ-wrap"><p class="occ-label">Liberty Church • Samaritan’s Purse</p><h1><?=esc($f['title'])?></h1><p class="occ-intro"><?=nl2br(esc($f['description']))?></p><p class="occ-deadline"><strong>Shoeboxes due: <?=esc($f['deadline'])?></strong></p>
<div><a class="occ-button" href="#contact">Get Involved</a><button class="occ-button occ-share" id="shareFeature">Share This Mission</button><span id="shareStatus" role="status"></span></div>
<section class="occ-card" style="margin-top:32px"><h2>A small box. A meaningful gift.</h2><p>Discover Operation Christmas Child and how your family can participate.</p>
<?php if($video):?><iframe class="occ-video" src="<?=esc($video)?>" title="Operation Christmas Child video" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen loading="lazy"></iframe><?php else:?><p>The church’s feature video will be available here soon.</p><?php endif;?>
</section><div class="occ-grid"><section class="occ-card"><h2>Pack a Shoebox</h2><p>Choose gifts with care, pray for the child who will receive your box, and bring your completed shoebox to Liberty Church by the deadline.</p><p>Check the official packing instructions for gift ideas and items to leave out.</p><a href="https://www.samaritanspurse.org/operation-christmas-child/pack-a-shoe-box/" target="_blank" rel="noopener">Official Shoebox Packing Guide ↗</a></section>
<section class="occ-card"><h2>Meet Your Organizers</h2><?php $contacts=array_filter(explode("\n",$f['organizers']));if(!$contacts):?><p>Organizer contact details will be posted here soon. You can reach the church team using the form below.</p><?php endif;foreach($contacts as $contact):$parts=explode('|',$contact,2);$phone=preg_replace('/[^0-9+]/','',$parts[1]??'');?><p><strong><?=esc(trim($parts[0]))?></strong><br><?php if($phone):?><a href="tel:<?=esc($phone)?>"><?=esc(trim($parts[1]))?></a><?php endif;?></p><?php endforeach;?></section></div>
<section class="occ-card" id="contact"><h2>Contact the Christmas Child Team</h2><p>Ask a question, offer to help, or let us know you’re participating.</p><?php if($notice):?><p class="occ-notice" role="status"><?=esc($notice)?></p><?php endif;?>
<form class="occ-form" method="post" action="/operation-christmas-child#contact"><input type="hidden" name="csrf_token" value="<?=esc(csrf_token())?>"><div class="occ-trap" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><label for="name">Name</label><input id="name" name="name" required maxlength="120" autocomplete="name"><label for="email">Email</label><input id="email" name="email" type="email" required maxlength="254" autocomplete="email"><label for="phone">Phone (optional)</label><input id="phone" name="phone" type="tel" maxlength="40" autocomplete="tel"><label for="message">Message</label><textarea id="message" name="message" required maxlength="5000" rows="5"></textarea><p>Your message goes to Liberty Church’s private feature inbox.</p><button class="occ-button" type="submit">Send Message</button></form></section></div></main><footer class="occ-footer">Liberty Church · Alexandria, Louisiana</footer><script src="/assets/site.js"></script><script src="/assets/js/feature.js"></script><script>
document.getElementById('shareFeature').addEventListener('click',async()=>{const data={title:'Operation Christmas Child at Liberty Church',url:'https://www.golibertychurch.com/operation-christmas-child'};try{if(navigator.share){await navigator.share(data);}else{await navigator.clipboard.writeText(data.url);document.getElementById('shareStatus').textContent=' Link copied!';}}catch(e){if(e.name!=='AbortError')document.getElementById('shareStatus').textContent=' Share this page using your browser’s share menu.';}});
</script></body></html>
