const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const base='http://127.0.0.1:8090';const browser=await chromium.launch({executablePath:process.env.PLANNER_CHROME_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 async function login(role){const context=await browser.newContext({viewport:{width:390,height:900}});const page=await context.newPage();await page.goto(base+'/php/admin/login.php');await page.locator('[name=username]').fill('qa_'+role);await page.locator('[name=password]').fill('local-test-only');await Promise.all([page.waitForURL('**/dashboard.php'),page.getByRole('button',{name:'Sign In'}).click()]);return {page,context};}
 function luminance(rgb){return rgb.slice(0,3).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0)}
 async function contrast(page,selector,bgSelector){const colors=await page.locator(selector).first().evaluate((node,bgSel)=>{const bg=bgSel?node.closest(bgSel):node;return [getComputedStyle(node).color,getComputedStyle(bg).backgroundColor].map(x=>x.match(/[\d.]+/g).map(Number));},bgSelector);const l=colors.map(luminance);assert.ok((Math.max(...l)+.05)/(Math.min(...l)+.05)>=4.5,'Readable contrast '+selector);}
 const {page,context}=await login('pastor');await page.goto(base+'/php/admin/service-planner/index.php');await page.locator('.service-history a').first().click();const id=new URL(page.url()).searchParams.get('service_id');const route=s=>base+`/php/admin/service-planner/index.php?service_id=${id}&section=${s}`;
 for(const width of [320,375,390,768,1366]){
  await page.setViewportSize({width,height:900});
  for(const path of ['/php/admin/users/index.php','/php/admin/users/new.php']){await page.goto(base+path);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${path} fits ${width}`);assert.equal(await page.locator('.resource-menu-inline').count(),0);}
  await page.goto(base+'/php/admin/users/index.php');const own=page.locator('.account-entry').filter({hasText:'qa_pastor'});assert.equal(await own.locator('form').count(),0);assert.equal(await own.getByRole('link',{name:'Edit',exact:true}).count(),1);
  const row=page.locator('.account-entry').filter({hasText:'qa_music_minister'});await row.getByRole('link',{name:'Edit',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Edit fits ${width}`);assert.equal(await page.locator('[name=role]').inputValue(),'music_minister');assert.equal(await page.locator('[name=csrf_token]').count(),1);
  for(const section of ['sermon','worship','media','announcements']){await page.goto(route(section));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${section} hero fits ${width}`);await contrast(page,'.planner-work-header h2','.planner-work-header');await contrast(page,'.planner-first-step','.planner-work-header');await contrast(page,'.planner-start-button');await page.locator('.planner-start-button').click();assert.equal(new URL(page.url()).hash,'#planner-work-start');assert.equal(await page.locator('#planner-work-start').count(),1);}
  // The one menu tab stays fixed at the left edge, including after scrolling.
  const tab=page.locator('.resource-nav-launcher');const before=await tab.boundingBox();await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));const after=await tab.boundingBox();assert.equal(before.y,after.y);assert.equal(after.x,0);assert.ok(after.height>=44);await tab.click();await page.waitForTimeout(250);assert.equal(await tab.getAttribute('aria-expanded'),'true');assert.ok((await page.locator('#adminResourceMenu').boundingBox()).x>=-1);assert.ok((await tab.boundingBox()).x+(await tab.boundingBox()).width<=width,'Open menu close tab fits screen');await page.keyboard.press('Escape');assert.equal(await tab.getAttribute('aria-expanded'),'false');
 }
 await page.setViewportSize({width:390,height:900});await page.goto(base+'/php/admin/users/index.php');await contrast(page,'.account-page-header h2','.account-page-header');await contrast(page,'.account-status.is-active');await page.screenshot({animations:'disabled',path:'docs/previews/accounts-mobile.png'});
 await page.goto(route('sermon'));await page.screenshot({animations:'disabled',path:'docs/previews/pastor-mobile-start.png'});await page.goto(route('worship'));await page.screenshot({animations:'disabled',path:'docs/previews/worship-mobile-start.png'});await page.goto(route('media'));await page.screenshot({animations:'disabled',path:'docs/previews/media-mobile-start.png'});
 // Exercise the existing account forms on a disposable QA account only.
 await page.goto(base+'/php/admin/users/new.php');await page.locator('[name=username]').fill('qa_mobile_account');await page.locator('[name=role]').selectOption('media');await page.locator('[name=password]').fill('local-test-only');await page.locator('[name=password_confirm]').fill('local-test-only');await Promise.all([page.waitForURL('**/users/index.php'),page.getByRole('button',{name:'Create user',exact:true}).click()]);let testRow=page.locator('.account-entry').filter({hasText:'qa_mobile_account'});assert.equal(await testRow.count(),1);await testRow.getByRole('link',{name:'Edit',exact:true}).click();await page.locator('[name=username]').fill('qa_mobile_account_with_a_long_username');await Promise.all([page.waitForURL('**/users/index.php'),page.getByRole('button',{name:'Save changes'}).click()]);testRow=page.locator('.account-entry').filter({hasText:'qa_mobile_account_with_a_long_username'});page.on('dialog',d=>d.accept());await Promise.all([page.waitForEvent('framenavigated'),testRow.getByRole('button',{name:'Disable',exact:true}).click()]);await page.waitForLoadState();assert.equal(await testRow.locator('.account-status').innerText(),'Disabled');await contrast(page,'.account-status.is-disabled');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Long username fits');await Promise.all([page.waitForEvent('framenavigated'),testRow.getByRole('button',{name:'Activate',exact:true}).click()]);await page.waitForLoadState();assert.equal(await testRow.locator('.account-status').innerText(),'Active');
 for(const role of ['admin','media','sound','music_minister','worship_team','youth_minister']){const {page:p,context:c}=await login(role);const res=await p.goto(base+'/php/admin/users/index.php');assert.equal(res.status(),role==='admin'?200:403,role+' keeps existing access');await c.close();}
 await context.close();await browser.close();console.log('Account list/new/edit, QA create/save/toggle, existing access, 320–1366px layouts, hero anchors/contrast, and fixed floating navigation passed.');
})().catch(e=>{console.error(e);process.exit(1)});
