const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({...(process.env.PLANNER_CHROME_EXECUTABLE?{executablePath:process.env.PLANNER_CHROME_EXECUTABLE}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const base=process.env.PLANNER_TEST_BASE||'http://127.0.0.1:8090'; if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw new Error('Use an isolated local server only.'); const errors=[];
 async function login(role,width=1366){const ctx=await browser.newContext({viewport:{width,height:900}});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/php/admin/login.php');await p.locator('[name=username]').fill('qa_'+role);await p.locator('[name=password]').fill('local-test-only');await Promise.all([p.waitForURL('**/dashboard.php'),p.getByRole('button',{name:'Sign In'}).click()]);return {ctx,p};}
 const {ctx:pastorCtx,p:pastor}=await login('pastor');await pastor.goto(base+'/php/admin/service-planner/index.php');await pastor.locator('.service-history a').first().click();const id=new URL(pastor.url()).searchParams.get('service_id'); const url=(s,extra='')=>base+`/php/admin/service-planner/index.php?service_id=${id}&section=${s}${extra}`;
 const roleCases={pastor:[1,1,1],admin:[1,1,1],music_minister:[0,1,0],media:[0,0,1],sound:[0,0,1],worship_team:[0,0,0],youth_minister:[0,0,0]};
 for(const [role,[sermon,worship,media]] of Object.entries(roleCases)){
   const {ctx,p}=await login(role); await p.goto(url('feed'));
   const nav=p.locator('.planner-nav-group');assert.equal(await nav.getByRole('link',{name:'Pastor',exact:true}).count(),sermon);assert.equal(await nav.getByRole('link',{name:'Music Minister',exact:true}).count(),worship);assert.equal(await nav.locator('.planner-station-menu').count(),media);
   for(const [section,allow] of [['sermon',sermon],['worship',worship],['media',media],['sheet',1],['notes',1]]){const res=await p.goto(url(section));assert.equal(res.status(),allow?200:403,`${role}:${section}`);}
   const response=await ctx.request.post(base+'/php/admin/service-planner/state.php',{form:{action:'sermon',service_id:id,revision:2,title:'Not authorized'}});assert.equal(response.status(),sermon?419:403);
   await ctx.close();
 }
 console.log('Existing role visibility, direct route gates, write gates, and CSRF checked.');
 const {ctx:mediaCtx,p:media}=await login('media'); const {ctx:phoneCtx,p:phone}=await login('sound',390);
 await media.goto(url('media','&computers[]=computer2&computers[]=computer3'));await phone.goto(url('media','&computers[]=computer2'));
 assert.equal(await media.locator('[data-station]').count(),2);assert.equal(await media.locator('.howto').count(),0);assert.equal(await media.locator('[data-planner-form]').count(),0);
 await media.locator('[data-task-key=computer2_pre_01]').check();await media.waitForFunction(()=>document.querySelector('#sync-message').textContent.includes('saved'));await phone.waitForFunction(()=>document.querySelector('[data-task-key=computer2_pre_01]').checked,{},{timeout:15000});
 assert.match(await phone.locator('[data-group-progress]').first().innerText(),/^1 of 3/);
 const second=media.locator('#computer2 .process-group').nth(1); await second.locator('summary').click(); await media.waitForTimeout(100);assert.equal(await media.locator('#computer2 .process-group[open]').count(),1);
 const gp=await Promise.all([media.waitForEvent('popup'),second.locator('[data-guide-popup]').first().click()]); const guide=gp[0]; await guide.waitForLoadState();assert.match(await guide.title(),/Open YouTube/);assert.equal(await guide.locator('.guide-steps li').count()>0,true);await guide.getByText('Update these instructions',{exact:true}).click();await guide.locator('[name=instructions]').fill('1. Open the approved service.\n2. Confirm the Sunday date.\nAsk the regular operator if unsure.');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jS1sAAAAASUVORK5CYII=','base64');await guide.locator('[name=screenshot]').setInputFiles({name:'reference.png',mimeType:'image/png',buffer:png});await Promise.all([guide.waitForURL(u=>!u.searchParams.has('edit')),guide.getByRole('button',{name:'Save instructions',exact:true}).click()]);assert.equal(await guide.locator('figure img').count(),1);assert.equal(await guide.locator('.guide-steps li').count(),2);await guide.getByRole('button',{name:'Close guide',exact:true}).click();assert.equal(guide.isClosed(),true);
 const popupPromise=media.waitForEvent('popup');await media.getByRole('link',{name:'Pop Out Checklist ↗'}).click();const popup=await popupPromise;await popup.waitForLoadState();assert.equal(await popup.locator('[data-station=computer2]').isVisible(),true);assert.equal(await popup.locator('[data-station=computer3]').isVisible(),false);await popup.locator('[data-station-switch=computer3]').click();assert.equal(await popup.locator('[data-station=computer3]').isVisible(),true);fs.mkdirSync('docs/previews',{recursive:true});await popup.screenshot({animations:'disabled',path:'docs/previews/service-checklist-popup.png'});await popup.locator('.planner-section-tabs').getByRole('link',{name:'Service Sheet',exact:true}).click();assert.equal(await popup.locator('#service-planner form').count(),0);await popup.locator('.planner-section-tabs').getByRole('link',{name:'Checklists',exact:true}).click();assert.equal(await popup.locator('[data-station]').count(),2);await popup.getByRole('button',{name:'Close',exact:true}).click();
 console.log('Shared phone/desktop saves, process accordions, screenshot guides, close controls, and two-station pop-out navigation checked.');
 await pastor.goto(url('announcements'));await pastor.locator('[name=announcement_notes]').fill('Sunday reminder: prepare the outreach graphic.');await pastor.getByRole('button',{name:'Save announcement notes'}).click();await pastor.waitForFunction(()=>document.querySelector('.save-message').textContent.includes('saved')||[...document.querySelectorAll('.save-message')].some(x=>x.textContent.includes('Saved')));
 await phone.goto(url('sheet'));assert.equal(await phone.locator('#service-planner form').count(),0);assert.equal(await phone.locator('[data-sermon-field=announcement_notes]').innerText(),'Sunday reminder: prepare the outreach graphic.');assert.match(await phone.locator('[data-sheet-announcements]').innerText(),/Upcoming outreach/);assert.doesNotMatch(await phone.locator('[data-sheet-announcements]').innerText(),/Expired event/);
 await media.goto(url('media','&computers[]=foh'));await media.locator('[name=foh_readiness]').selectOption('READY');await media.getByRole('button',{name:'Save house sound status'}).click();await phone.waitForFunction(()=>document.querySelector('[data-status-key=foh]').textContent==='READY',{},{timeout:15000});
 await pastor.goto(url('sermon'));await pastor.locator('[name=title]').fill('A Shared Sunday');await pastor.getByRole('button',{name:'Save sermon information'}).click();await pastor.waitForFunction(()=>[...document.querySelectorAll('.save-message')].some(x=>x.textContent.includes('Saved')));await phone.waitForFunction(()=>document.querySelector('[data-sermon-field=title]').textContent==='A Shared Sunday',{},{timeout:15000});assert.equal(await phone.locator('[data-sermon-field=announcement_notes]').innerText(),'Sunday reminder: prepare the outreach graphic.');
 const {ctx:musicCtx,p:music}=await login('music_minister');await music.goto(url('worship'));assert.equal(await music.locator('[data-media-ready-count]').innerText(),'1 of 5 stations ready');
 await media.goto(base+'/php/admin/announcements/index.php?category=youth');assert.match(await media.locator('tbody').innerText(),/Youth night/);assert.doesNotMatch(await media.locator('tbody').innerText(),/Upcoming outreach/);await media.getByRole('link',{name:'+ New Announcement',exact:true}).click();assert.equal(await media.locator('[name=category]').inputValue(),'youth');
 fs.mkdirSync('docs/previews',{recursive:true});
 for(const width of [375,390,768,1366]){await media.setViewportSize({width,height:900});for(const section of ['feed','media','sheet','notes']){await media.goto(url(section,section==='media'?'&computers[]=computer2&computers[]=computer3':''));assert.equal(await media.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`No overflow ${width} ${section}`);}
 await media.goto(url('media','&computers[]=computer2&computers[]=computer3'));if(width===390){await media.locator('#computer2').scrollIntoViewIfNeeded();await media.screenshot({animations:'disabled',path:'docs/previews/service-planner-mobile.png'});await media.locator('.resource-nav-launcher').click();await media.waitForTimeout(250);assert.equal(await media.locator('#adminResourceMenu').evaluate(el=>el.getBoundingClientRect().left>=0),true);await media.screenshot({animations:'disabled',path:'docs/previews/service-planner-mobile-menu.png'});await media.locator('.resource-nav-backdrop').click({position:{x:380,y:400}});}if(width===1366){assert.equal(await media.locator('.resource-nav-launcher').isVisible(),true);assert.equal(await media.locator('#adminResourceMenu').evaluate(el=>el.getBoundingClientRect().right<=1),true);await media.locator('.resource-nav-launcher').click();await media.waitForTimeout(250);await media.screenshot({animations:'disabled',path:'docs/previews/service-planner-desktop.png'});}}
 await media.goto(url('sheet'));await media.screenshot({animations:'disabled',path:'docs/previews/service-sheet-desktop.png'});
 // Real mobile editor coverage: saved and freshly added songs must use the same footer controls.
 await music.setViewportSize({width:390,height:900});await music.goto(url('worship'));
 assert.match(await music.locator('.planner-work-header').innerText(),/MUSIC MINISTER WORKSPACE/i);
 assert.equal(await music.locator('.song-head button').count(),0);
 await music.locator('.song').nth(1).locator('[data-song-action=up]').click();
 assert.equal(await music.locator('[data-song-field=title]').first().inputValue(),'Great Are You Lord');
 await music.locator('.song').first().locator('[data-song-action=down]').click();
 assert.equal(await music.locator('[data-song-field=title]').first().inputValue(),'Goodness of God');
 await music.locator('#add-song').click();const newSong=music.locator('.song').last();
 await newSong.locator('[data-song-field=title]').fill('QA New mobile song');await newSong.locator('[data-song-field=key]').fill('E');await newSong.locator('[data-song-field=lead]').fill('QA Lead');
 assert.equal(await newSong.locator('[data-song-action=down]').isDisabled(),true);
 await newSong.locator('.song-extra-fields summary').click();await newSong.locator('[data-song-field=notes]').fill('Multiline mobile notes.\nKeep the intro soft.');
 for(const song of await music.locator('.song').all()){
   const buttons=await song.locator('.song-actions button').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return {top:r.top,height:r.height};}));
   assert.equal(buttons.every(b=>Math.abs(b.top-buttons[0].top)<1 && b.height>=44),true,'Footer buttons share one touch-friendly row');
   assert.equal(await song.evaluate(node=>{const footer=node.querySelector('.song-actions').getBoundingClientRect();return [...node.querySelectorAll('[data-song-field]')].filter(input=>input.checkVisibility()).every(input=>input.getBoundingClientRect().bottom<=footer.top);}),true,'Song actions belong below every field');
 }
 await newSong.locator('[data-song-action=remove]').click();assert.equal(await music.locator('.song').count(),2);
 await music.getByRole('button',{name:'Save worship plan',exact:true}).click();await music.waitForFunction(()=>[...document.querySelectorAll('.save-message')].some(x=>x.textContent.includes('Saved')));
 await music.reload();assert.equal(await music.locator('[data-song-field=title]').first().inputValue(),'Goodness of God');
 await music.evaluate(()=>scrollTo(0,0));await music.screenshot({animations:'disabled',path:'docs/previews/worship-mobile-start.png'});await music.locator('.song').first().scrollIntoViewIfNeeded();await music.screenshot({animations:'disabled',path:'docs/previews/worship-mobile-song.png'});
 for(const width of [320,375,390,768]){
   await music.setViewportSize({width,height:900});await pastor.setViewportSize({width,height:900});await media.setViewportSize({width,height:900});
   await music.goto(url('worship'));assert.equal(await music.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Worship fits ${width}`);
   for(const section of ['sermon','announcements']){await pastor.goto(url(section));assert.equal(await pastor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Pastor ${section} fits ${width}`);assert.match(await pastor.locator('.planner-work-header').innerText(),/PASTOR WORKSPACE/i);}
   const albumPage='/php/admin/youth-albums/index.php';
   const paths=['/php/admin/media/index.php','/php/admin/announcements/index.php','/php/admin/announcements/new.php','/php/admin/youth-scripture/index.php',albumPage,'/php/admin/youth-albums/new.php','/php/admin/features/index.php','/php/admin/stream/index.php'];
   for(const path of paths){const response=await media.goto(base+path);assert.equal(response.status(),200,path);assert.equal(await media.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${path} fits ${width}`);}
   await media.goto(base+albumPage);const album=media.locator('.album-card').filter({hasText:'QA Youth gallery'});await album.getByRole('link',{name:'Manage Photos',exact:true}).click();assert.equal(await media.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Media uploads fit ${width}`);
 }
 await pastor.setViewportSize({width:390,height:900});await pastor.goto(url('sermon'));await pastor.screenshot({animations:'disabled',path:'docs/previews/pastor-mobile-start.png'});
 await media.setViewportSize({width:390,height:900});await media.goto(base+'/php/admin/announcements/index.php');await media.screenshot({animations:'disabled',path:'docs/previews/announcements-mobile.png'});
 console.log('Mobile worship footer controls, song ordering/add/remove/save, Pastor introductions, and all implemented MMS screens checked at 320/375/390/768px.');
 await pastor.goto(url('feed'));await pastor.locator('.tool-detail summary').click();await pastor.getByRole('button',{name:'Archive this Sunday'}).click();await pastor.waitForFunction(()=>document.querySelector('#service-planner').dataset.archived==='1');
 await music.goto(url('worship'));assert.equal(await music.locator('[name=ready]').isDisabled(),true);assert.equal(await music.locator('#add-song').count(),0);
 await phone.goto(url('media','&computers[]=computer2'));assert.equal(await phone.locator('[data-task-key]').first().isDisabled(),true);
 const standalone=await mediaCtx.newPage();await standalone.goto(base+'/php/admin/service-planner/guide.php?task=computer2_pre_04&edit=1');await standalone.locator('[name=instructions]').fill('1. A later manual update.');await Promise.all([standalone.waitForURL(u=>!u.searchParams.has('edit')),standalone.getByRole('button',{name:'Save instructions',exact:true}).click()]);
 await phone.goto(base+`/php/admin/service-planner/guide.php?service_id=${id}&task=computer2_pre_04`);assert.match(await phone.locator('.guide-steps').innerText(),/approved service/);assert.equal(await phone.getByText('Update these instructions',{exact:true}).count(),0);
 console.log('Archived desktop/mobile views stay read-only; standalone guide edits preserve historical instructions.');
 assert.deepEqual(errors,[]);console.log('Announcement notes, FOH readiness, youth filters, read-only sheet, and 375/390/768/1366px layouts checked.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
